package de.slisson.mps.richtext.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class RichTextUtil {
  public static SNode createSingleWordFromText(String text) {
    SNode w = SConceptOperations.createNewNode("de.slisson.mps.richtext.structure.Word", null);
    Word_Behavior.call_setText_2008781830388272163(w, text);
    return w;
  }

  public static SNode createTextFromSingleString(String text) {
    SNode t = SConceptOperations.createNewNode("de.slisson.mps.richtext.structure.Text", null);
    ListSequence.fromList(SLinkOperations.getTargets(t, "words", true)).addElement(createSingleWordFromText(text));
    return t;
  }
}
