package de.slisson.mps.richtext.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.model.SNode;

public class Word_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IWord_BehaviorDescriptor {
  public Word_BehaviorDescriptor() {
  }

  public Iterable<String> virtual_getTransformKeys_9006904477154868758(SConcept thisConcept) {
    return Word_Behavior.virtual_getTransformKeys_9006904477154868758(thisConcept);
  }

  public String virtual_toTextString_4433012599261204765(SNode thisNode) {
    return Word_Behavior.virtual_toTextString_4433012599261204765(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.slisson.mps.richtext.structure.Word";
  }
}
