package de.slisson.mps.editor.multiline.cells;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.CellAction;
import jetbrains.mps.openapi.editor.EditorContext;

public class NewLineAction implements CellAction {
  private EditorCell_Word myWordCell;


  public NewLineAction(EditorCell_Word wordCell) {
    myWordCell = wordCell;
  }



  public boolean canExecute(EditorContext context) {
    return true;
  }

  public void execute(EditorContext context) {
    myWordCell.insertText("\n");
  }

  public boolean executeInCommand() {
    return false;
  }

  public String getDescriptionText() {
    return "Insert New Line";
  }
}
