package de.slisson.mps.richtext.customcell.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.StaticScope;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("de.slisson.mps.richtext.customcell.structure.CellModel_CustomFactory").super_("jetbrains.mps.lang.editor.structure.EditorCellModel").parents("jetbrains.mps.lang.editor.structure.EditorCellModel").children(new String[]{"childCellModel", "factoryMethod"}, new boolean[]{false, false}).alias("custom factory", "").create();
      case 1:
        return new ConceptDescriptorBuilder("de.slisson.mps.richtext.customcell.structure.ConceptFunctionParameter_cell").super_("jetbrains.mps.baseLanguage.structure.ConceptFunctionParameter").parents("jetbrains.mps.baseLanguage.structure.ConceptFunctionParameter", "jetbrains.mps.lang.core.structure.IDontSubstituteByDefault").alias("cell", "").staticScope(StaticScope.NONE).create();
      case 2:
        return new ConceptDescriptorBuilder("de.slisson.mps.richtext.customcell.structure.QueryFunction_Cell").super_("jetbrains.mps.baseLanguage.structure.ConceptFunction").parents("jetbrains.mps.baseLanguage.structure.ConceptFunction").alias("cell", "").staticScope(StaticScope.NONE).create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"de.slisson.mps.richtext.customcell.structure.CellModel_CustomFactory", "de.slisson.mps.richtext.customcell.structure.ConceptFunctionParameter_cell", "de.slisson.mps.richtext.customcell.structure.QueryFunction_Cell"};
}
