package de.slisson.mps.richtext.customcell.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new CellModel_CustomFactory_BehaviorDescriptor();
      case 2:
        return new QueryFunction_Cell_BehaviorDescriptor();
      case 1:
        return new ConceptFunctionParameter_cell_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"de.slisson.mps.richtext.customcell.structure.CellModel_CustomFactory", "de.slisson.mps.richtext.customcell.structure.ConceptFunctionParameter_cell", "de.slisson.mps.richtext.customcell.structure.QueryFunction_Cell"};
}
