package de.slisson.mps.richtext.customcell.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class CellModel_CustomFactory_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getOpeningText_1220339714057(SNode thisNode) {
    return "$";
  }

  public static boolean virtual_isCellIdInitialized_1229948571177(SNode thisNode) {
    return true;
  }

  public static String virtual_getClosingText_1220339738643(SNode thisNode) {
    return "$";
  }
}
