package de.slisson.mps.richtext.vcshandler;

/*Generated by MPS */

import com.intellij.openapi.components.ApplicationComponent;
import jetbrains.mps.vcs.diff.ui.common.DiffHandlerRegistry;

public class RichtextVcsComponent implements ApplicationComponent {
  private RichtextDiffHandler myDiffHandler = new RichtextDiffHandler();

  @Override
  public void initComponent() {
    DiffHandlerRegistry.instance().register(myDiffHandler);
  }

  @Override
  public void disposeComponent() {
    DiffHandlerRegistry.instance().unregister(myDiffHandler);
  }

  @Override
  public String getComponentName() {
    return "Richtext VCS Handler";
  }
}
