package de.slisson.mps.richtext.vcshandler;

/*Generated by MPS */

import com.intellij.openapi.components.ApplicationComponent;
import jetbrains.mps.vcs.diff.ui.common.DiffHandlerRegistry;

public class RichtextVcsComponent implements ApplicationComponent {
  private RichtextDiffHandler myRichtextDiffHandler = new RichtextDiffHandler();
  private MultilineDiffHandler myMultilineDiffHandler = new MultilineDiffHandler();

  @Override
  public void initComponent() {
    DiffHandlerRegistry.instance().register(myRichtextDiffHandler);
    DiffHandlerRegistry.instance().register(myMultilineDiffHandler);
  }

  @Override
  public void disposeComponent() {
    DiffHandlerRegistry.instance().unregister(myRichtextDiffHandler);
    DiffHandlerRegistry.instance().unregister(myMultilineDiffHandler);
  }

  @Override
  public String getComponentName() {
    return "Richtext VCS Handler";
  }
}
