package jetbrains.mps.editor.richtext.actions;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.action.NodeSetupContext;
import jetbrains.mps.editor.richtext.behavior.Text_Behavior;

public class QueriesGenerated {
  public static void nodeFactory_NodeSetup_Text_793221525401868616(final IOperationContext operationContext, final NodeSetupContext _context) {
    Text_Behavior.call_ensureNormalized_3868187941957822880(_context.getNewNode());
  }
}
