package de.slisson.mps.richtext.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import de.slisson.mps.richtext.behavior.Word_Behavior;

public class Word_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append(Word_Behavior.call_getText_257181264606026343(node));
  }
}
