package de.slisson.mps.richtext.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import com.intellij.openapi.actionSystem.Shortcut;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import javax.swing.KeyStroke;

public class RichtextSelectionHandling_KeymapChanges extends BaseKeymapChanges {
  public RichtextSelectionHandling_KeymapChanges() {
    // simple 
    addSimpleShortcut("de.slisson.mps.richtext.plugin.RichtextSelectionLeft_Action", getShortcut("shift LEFT"));
    addSimpleShortcut("de.slisson.mps.richtext.plugin.RichtextSelectionLocalEnd_Action", getShortcut("alt shift RIGHT"));
    addSimpleShortcut("de.slisson.mps.richtext.plugin.RichtextSelectionLocalHome_Action", getShortcut("alt shift LEFT"));
    addSimpleShortcut("de.slisson.mps.richtext.plugin.RichtextSelectionRight_Action", getShortcut("shift RIGHT"));
    // simple parameterized 
    // complex 
  }

  public String getScheme() {
    return "$default";
  }

  public static Shortcut getShortcut(String stroke) {
    return new KeyboardShortcut(KeyStroke.getKeyStroke(stroke), null);
  }
}
