package de.slisson.mps.richtext.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import java.util.List;
import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public class Richtext_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("de.slisson.mps.richtext");

  public Richtext_ApplicationPlugin() {
  }

  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters 
    addAction(new RichtextSelectionLeft_Action());
    addAction(new RichtextSelectionLocalEnd_Action());
    addAction(new RichtextSelectionLocalHome_Action());
    addAction(new RichtextSelectionRight_Action());
    // groups 
  }

  public List<BaseKeymapChanges> initKeymaps() {
    List<BaseKeymapChanges> res = ListSequence.fromList(new ArrayList<BaseKeymapChanges>());
    ListSequence.fromList(res).addElement(new RichtextSelectionHandling_KeymapChanges());
    return res;
  }
}
