package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class CellModel_NextEditor_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor {
  public CellModel_NextEditor_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.CellModel_NextEditor";
  }
}
