package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class IndentLayoutWrapIndentFactorStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor {
  public IndentLayoutWrapIndentFactorStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.IndentLayoutWrapIndentFactorStyleClassItem";
  }
}
