package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class LayoutConstraintStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor implements ILegacyStyleClassItem_BehaviorDescriptor {
  public LayoutConstraintStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.LayoutConstraintStyleClassItem";
  }
}
