package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class MaxWidthStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor implements ILegacyStyleClassItem_BehaviorDescriptor {
  public MaxWidthStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.MaxWidthStyleClassItem";
  }
}
