package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class NavigatableReferenceStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor implements ILegacyStyleClassItem_BehaviorDescriptor {
  public NavigatableReferenceStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.NavigatableReferenceStyleClassItem";
  }
}
