package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class ParametersInformationStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor implements ILegacyStyleClassItem_BehaviorDescriptor {
  public ParametersInformationStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.ParametersInformationStyleClassItem";
  }
}
