package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class PositionStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor implements ILegacyStyleClassItem_BehaviorDescriptor {
  public PositionStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.PositionStyleClassItem";
  }
}
