package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class QueryFunction_Float_BehaviorDescriptor extends QueryFunction_StyleParameter_BehaviorDescriptor {
  public QueryFunction_Float_BehaviorDescriptor() {
  }

  public SNode virtual_getExpectedReturnType_1213877374441(SNode thisNode) {
    return QueryFunction_Float_Behavior.virtual_getExpectedReturnType_1213877374441(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.QueryFunction_Float";
  }
}
