package jetbrains.mps.lang.editor.behavior;

/*Generated by MPS */


public class UnderlinedStyleClassItem_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor implements ILegacyStyleClassItem_BehaviorDescriptor {
  public UnderlinedStyleClassItem_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.editor.structure.UnderlinedStyleClassItem";
  }
}
