package jetbrains.mps.editor.multiline.runtime;

/*Generated by MPS */

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.lang3.StringUtils;

public class MultilineUtil {
  public static String unescapeText(String escaped) {
    return StringEscapeUtils.unescapeJava(StringUtils.defaultString(escaped));
  }

  public static String escapeText(String unescaped) {
    return StringEscapeUtils.escapeJava(StringUtils.defaultString(unescaped));
  }
}
