package jetbrains.mps.editor.richtext.customcell.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.EditorCellModel_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class CellModel_CustomFactory_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor {
  public CellModel_CustomFactory_BehaviorDescriptor() {
  }

  public String virtual_getClosingText_1220339738643(SNode thisNode) {
    return CellModel_CustomFactory_Behavior.virtual_getClosingText_1220339738643(thisNode);
  }

  public String virtual_getOpeningText_1220339714057(SNode thisNode) {
    return CellModel_CustomFactory_Behavior.virtual_getOpeningText_1220339714057(thisNode);
  }

  public boolean virtual_isCellIdInitialized_1229948571177(SNode thisNode) {
    return CellModel_CustomFactory_Behavior.virtual_isCellIdInitialized_1229948571177(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.richtext.customcell.structure.CellModel_CustomFactory";
  }
}
