package de.slisson.mps.editor.multiline.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class CellModel_Multiline_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getClosingText_1220339738643(SNode thisNode) {
    return BehaviorReflection.invokeSuper(String.class, thisNode, "jetbrains.mps.lang.editor.structure.CellModel_Property", "virtual_getClosingText_1220339738643", new Object[]{}) + "\\n";
  }
}
