package de.slisson.mps.richtext.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import de.slisson.mps.richtext.behavior.Text_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class fix_Text_normalize_QuickFix extends QuickFix_Runtime {
  public fix_Text_normalize_QuickFix() {
  }

  public String getDescription(SNode node) {
    return "Normalize Text Structure";
  }

  public void execute(SNode node) {
    Text_Behavior.call_ensureNormalized_3868187941957822880(SNodeOperations.getAncestor(node, "de.slisson.mps.richtext.structure.Text", true, false));
  }
}
