package de.slisson.mps.richtext.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("92d2ea16-5a42-4fdf-a676-c7604efe3504(de.slisson.mps.richtext)"), PersistenceFacade.getInstance().createModelReference("r:fa163aad-8c9b-4361-aa5e-88392679736a(de.slisson.mps.richtext.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new Text_Normalize_Intention());
  }
}
