package jetbrains.mps.editor.richtext.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;

public interface IWord_BehaviorDescriptor {
  public String virtual_toTextString_4433012599261204765(SNode thisNode);
  public Iterable<String> virtual_getTransformKeys_9006904477154868758(SConcept thisConcept);
}
