package jetbrains.mps.editor.richtext.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.Collections;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class IWord_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_toTextString_4433012599261204765(SNode thisNode) {
    return null;
  }

  public static Iterable<String> virtual_getTransformKeys_9006904477154868758(SAbstractConcept thisConcept) {
    return Sequence.fromIterable(Collections.<String>emptyList());
  }

  @Deprecated
  public static String call_toTextString_4433012599261204765(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_toTextString_4433012599261204765", new Object[]{});
  }

  @Deprecated
  public static String callSuper_toTextString_4433012599261204765(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "jetbrains.mps.editor.richtext.structure.IWord"), callerConceptFqName, "virtual_toTextString_4433012599261204765", new Class[]{SNode.class}, new Object[]{});
  }
}
