package jetbrains.mps.editor.richtext.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Text_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Text_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.richtext.structure.Text";
  }
}
