package jetbrains.mps.vcs.diff.ui.common;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import java.awt.Graphics;

public interface DiffHandler {
  public boolean canHandle(ChangeEditorMessage message, EditorComponent editor);
  public Bounds getBounds(ChangeEditorMessage message, EditorComponent editor);
  public EditorCell getCell(ChangeEditorMessage message, EditorComponent editor);
  public boolean acceptCell(ChangeEditorMessage message, EditorComponent editor, jetbrains.mps.nodeEditor.cells.EditorCell cell);
  public void paint(Graphics g, ChangeEditorMessage message, EditorComponent editor, jetbrains.mps.nodeEditor.cells.EditorCell cell);
}
