package jetbrains.mps.vcs.diff.ui.common;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import java.awt.Graphics;

public interface DiffHandler {
  public boolean canHandle(ChangeEditorMessage message);
  public Bounds getBounds(EditorComponent component, ChangeEditorMessage message);
  public EditorCell getCell(ChangeEditorMessage message, jetbrains.mps.openapi.editor.EditorComponent editor);
  public boolean acceptCell(ChangeEditorMessage message, jetbrains.mps.openapi.editor.EditorComponent editor, EditorCell cell);
  public void paint(Graphics g, ChangeEditorMessage messages, EditorCell cell);
}
