package jetbrains.mps.vcs.diff.ui.common;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;
import java.util.Collections;

public class DiffHandlerRegistry {
  private static DiffHandlerRegistry ourInstance = new DiffHandlerRegistry();


  public static DiffHandlerRegistry instance() {
    return ourInstance;
  }


  private List<DiffHandler> myHandlers = new ArrayList<DiffHandler>();



  public void register(DiffHandler handler) {
    myHandlers.add(handler);
  }



  public void unregister(DiffHandler handler) {
    myHandlers.remove(handler);
  }



  public List<DiffHandler> getHandlers() {
    return Collections.unmodifiableList(myHandlers);
  }
}
