package jetbrains.mps.samples.richtext.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.StatementList_BehaviorDescriptor;
import de.slisson.mps.richtext.behavior.IWord_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import de.slisson.mps.richtext.behavior.IWord_Behavior;
import org.jetbrains.mps.openapi.model.SNode;

public class EmbeddedCode_BehaviorDescriptor extends StatementList_BehaviorDescriptor implements IWord_BehaviorDescriptor {
  public EmbeddedCode_BehaviorDescriptor() {
  }

  public Iterable<String> virtual_getTransformKeys_9006904477154868758(SConcept thisConcept) {
    return IWord_Behavior.virtual_getTransformKeys_9006904477154868758(thisConcept);
  }

  public String virtual_toTextString_4433012599261204765(SNode thisNode) {
    return IWord_Behavior.virtual_toTextString_4433012599261204765(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.samples.richtext.structure.EmbeddedCode";
  }
}
