package jetbrains.mps.samples.richtext.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class MultilineString_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public MultilineString_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.samples.richtext.structure.MultilineString";
  }
}
