package jetbrains.mps.samples.richtext.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Paragraph_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Paragraph_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.samples.richtext.structure.Paragraph";
  }
}
