package jetbrains.mps.vcs.diff.ui.common;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import java.util.concurrent.atomic.AtomicReference;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.vcs.diff.changes.ModelChange;
import jetbrains.mps.vcs.diff.ChangeSet;
import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;
import jetbrains.mps.util.DisjointSets;
import java.util.Set;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import jetbrains.mps.nodeEditor.cells.EditorCell;

@GeneratedClass(node = "r:07568eb8-30c0-4bb3-9dcb-50ee4b8de59a(jetbrains.mps.vcs.diff.ui.common)/4652592318748337213", model = "r:07568eb8-30c0-4bb3-9dcb-50ee4b8de59a(jetbrains.mps.vcs.diff.ui.common)")
public abstract class ChangeGroupLayout {
  private ChangeEditorMessage.ConflictChecker myConflictChecker;
  protected boolean myInspector = false;
  private boolean myMergeAdjacent;
  private final AtomicReference<List<ChangeGroup>> myChangeGroups = new AtomicReference<>();
  private List<ChangeGroupInvalidateListener> myInvalidateListeners = ListSequence.fromList(new ArrayList<ChangeGroupInvalidateListener>());
  private boolean myIsMerge;


  protected ChangeGroupLayout(@Nullable ChangeEditorMessage.ConflictChecker conflictChecker, boolean inspector, boolean mergeAdjacent) {
    myConflictChecker = conflictChecker;
    myInspector = inspector;
    myMergeAdjacent = mergeAdjacent;
  }

  @NotNull
  public abstract EditorComponent getLeftComponent();

  @NotNull
  public abstract EditorComponent getRightComponent();

  public boolean isValid() {
    return !(getLeftComponent().isDisposed() || getRightComponent().isDisposed());
  }

  protected abstract List<ChangeEditorMessage> getLeftMessages(ModelChange change);

  protected abstract List<ChangeEditorMessage> getRightMessages(ModelChange change);

  @Nullable
  protected abstract ChangeSet getChangeSet();

  public void setIsMerge() {
    myIsMerge = true;
  }

  public boolean isMerge() {
    return myIsMerge;
  }

  private List<ChangeGroup> calculateChangeGroups() {
    final Map<ModelChange, Bounds> left = MapSequence.fromMap(new HashMap<ModelChange, Bounds>());
    final Map<ModelChange, Bounds> right = MapSequence.fromMap(new HashMap<ModelChange, Bounds>());

    List<ModelChange> changes = ListSequence.fromList(new ArrayList<ModelChange>());

    for (ModelChange change : ListSequence.fromList(check_cuq72k_a5a62(getChangeSet(), this))) {
      Bounds leftBounds = findBounds(getLeftMessages(change), getLeftComponent());
      Bounds rightBounds = findBounds(getRightMessages(change), getRightComponent());

      if (leftBounds.length() <= 0 && rightBounds.length() <= 0) {
        continue;
      }

      ListSequence.fromList(changes).addElement(change);
      MapSequence.fromMap(left).put(change, leftBounds);
      MapSequence.fromMap(right).put(change, rightBounds);
    }

    DisjointSets<ModelChange> ds = new DisjointSets<ModelChange>(changes);
    boolean trackMovedNodes = (myIsMerge ? DiffSettingsUtil.getTrackMovedNodesMergeOption() : DiffSettingsUtil.getTrackMovedNodesDiffOption());
    uniteOverlapping(ds, changes, left, right, trackMovedNodes);
    uniteOverlapping(ds, changes, right, left, trackMovedNodes);
    List<ChangeGroup> list = ListSequence.fromList(new ArrayList<ChangeGroup>());
    for (Set<ModelChange> s : Sequence.fromIterable(ds.getSets())) {
      Bounds lb = SetSequence.fromSet(s).select((ch) -> MapSequence.fromMap(left).get(ch)).reduceLeft((a, b) -> a.merge(b));
      Bounds rb = SetSequence.fromSet(s).select((ch) -> MapSequence.fromMap(right).get(ch)).reduceLeft((a, b) -> a.merge(b));
      List<ModelChange> sortedChanges = SetSequence.fromSet(s).sort((ch) -> (int) MapSequence.fromMap(right).get(ch).start(), true).sort((ch) -> (int) MapSequence.fromMap(left).get(ch).start(), true).toList();
      ListSequence.fromList(list).addElement(new ChangeGroup(lb, rb, sortedChanges, myConflictChecker));
    }
    return ListSequence.fromList(list).sort((g) -> (int) g.getLeftBounds().start(), true).toList();
  }

  private void uniteOverlapping(DisjointSets<ModelChange> ds, List<ModelChange> changes, final Map<ModelChange, Bounds> primary, Map<ModelChange, Bounds> secondary, boolean trackMovedNodes) {
    List<ModelChange> sorted = ListSequence.fromList(changes).sort((ch) -> (int) MapSequence.fromMap(primary).get(ch).start(), true).toList();
    int size = ListSequence.fromList(sorted).count();
    for (int a = 0; a < size; a++) {
      ModelChange changeA = ListSequence.fromList(sorted).getElement(a);
      Bounds boundsA = MapSequence.fromMap(primary).get(changeA);
      if (!(trackMovedNodes) && areBoundsSeparate(boundsA, boundsA, myMergeAdjacent, trackMovedNodes)) {
        continue;
      }
      int endA = (int) boundsA.end();
      for (int b = a + 1; b < size; b++) {
        ModelChange changeB = ListSequence.fromList(sorted).getElement(b);
        Bounds boundsB = MapSequence.fromMap(primary).get(changeB);
        if ((int) boundsB.start() > endA) {
          break;
        }
        if (!(areBoundsSeparate(boundsA, boundsB, myMergeAdjacent, trackMovedNodes)) && (!(trackMovedNodes) || MapSequence.fromMap(secondary).get(changeA).containsPart(MapSequence.fromMap(secondary).get(changeB)) || MapSequence.fromMap(secondary).get(changeB).containsPart(MapSequence.fromMap(secondary).get(changeA)))) {
          ds.unite(changeA, changeB);
        }
      }
    }
  }

  public void addInvalidateListener(@NotNull ChangeGroupInvalidateListener listener) {
    ListSequence.fromList(myInvalidateListeners).addElement(listener);
  }

  public void removeInvalidateListener(@NotNull ChangeGroupInvalidateListener listener) {
    ListSequence.fromList(myInvalidateListeners).removeElement(listener);
  }

  @NotNull
  public List<ChangeGroup> getChangeGroups() {
    List<ChangeGroup> result = myChangeGroups.get();
    if (result == null) {
      result = calculateChangeGroups();
      boolean success = myChangeGroups.compareAndSet(null, result);
      if (!(success)) {
        return myChangeGroups.get();
      }
    }
    return result;
  }

  public void invalidate() {
    myChangeGroups.set(null);
    ListSequence.fromList(myInvalidateListeners).visitAll((it) -> it.changeGroupsInvalidated());
  }

  public int getEditorVerticalOffset() {
    if (myInspector) {
      return 0;
    } else {
      assert getLeftComponent().getExternalComponent().getY() == getRightComponent().getExternalComponent().getY();
      return getLeftComponent().getExternalComponent().getY();
    }
  }

  private static Bounds findBounds(Iterable<ChangeEditorMessage> messages, final EditorComponent editorComponent) {
    Bounds bounds = null;
    if (Sequence.fromIterable(messages).isNotEmpty()) {
      bounds = Sequence.fromIterable(messages).select((m) -> m.getBounds(editorComponent)).where((b) -> b.length() > 0).reduceLeft((a, b) -> a.merge(b));
    }
    if (bounds == null || bounds.length() <= 0) {
      int y = check_cuq72k_a0a0c0ob(check_cuq72k_a0a0a2a04(editorComponent));
      return new Bounds(y, y);
    } else {
      return bounds;
    }
  }

  private static boolean areBoundsSeparate(Bounds a, Bounds b, boolean canBeAdjacent, boolean trackMovedNodes) {
    if (trackMovedNodes) {
      if (a.length() <= 2 && b.length() <= 2) {
        return true;
      }
      if (!(canBeAdjacent)) {
        return (int) a.start() != (int) b.start() || (int) a.end() != (int) b.end();
      }
    }
    int tolerance = (canBeAdjacent ? 0 : 1);
    return (int) a.end() - tolerance < (int) b.start() || (int) b.end() - tolerance < (int) a.start();
  }
  private static List<ModelChange> check_cuq72k_a5a62(ChangeSet checkedDotOperand, ChangeGroupLayout checkedDotThisExpression) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getModelChanges();
    }
    return null;
  }
  private static int check_cuq72k_a0a0c0ob(EditorCell checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getY();
    }
    return 0;
  }
  private static EditorCell check_cuq72k_a0a0a2a04(EditorComponent checkedDotOperand) {
    if (null != checkedDotOperand) {
      return checkedDotOperand.getRootCell();
    }
    return null;
  }
}
